let leyenda1 = "Cuenta una preciosa leyenda el origen del volcán Popocatépetl y del volcán con perfil de mujer, conocida como la ‘Mujer dormida’.\nHace mucho, mucho tiempo, gobernó entre los aztecas un hombre bueno y justo, al que todos querían muchísimo. Este emperador tuvo una hija, hermosa e inteligente. Según iba creciendo, sus dones aumentaban, hasta tal punto que su padre temía no encontrar una pareja lo suficientemente valiosa para ella."
leyenda1 += "\n Sin embargo, su hija, de nombre Izta, ya se había enamorado de un valiente guerrero, muy popular entre todos por sus victorias. Pero por supuesto, ambos jóvenes llevaban su amor en secreto. \n El guerrero lucha por la mano de Izta\n En una ocasión, el imperio se vio amenazado por un enemigo muy fuerte. El emperador estaba tan preocupado, que llamó a sus tres mejores guerreros. Entre ellos estaba Popocatépetl, el guerrero del que su hija se había enamorado en secreto. \n – Os he mandado llamar porque sois los mejores y confío en vosotros- dijo el emperador- Esta vez pienso pagar con algo más que gratitud vuestra honestidad y coraje. Aquel quien consiga derrotar al enemigo, gobernará el imperio y se ganará la mano de mi hija. \n La joven miró a Popocatépetl y sonrió. Estaba totalmente segura de que ganaría a los otros dos guerreros. Y él, por supuesto, partió con la gran ilusión y la fuerza del amor de la joven Izta, lo que le hizo mucho más valiente."
leyenda1 += "\n El joven guerrero enamorado comenzó a ganar batallas, y sus dos oponentes empezaron a envidiarle hasta tal punto, que tramaron una trampa para deshacerse de él. Un día, le acompañaron hasta la línea enemiga y sin que se diera cuenta, huyeron y le dejaron solo. \n Al cabo de unos días, al ver que no regresaba, mandaron un mensaje al emperador anunciando su muerte. La joven Izta, al escucharlo, enfermó y murió de pena a los dos días. \n El regreso del guerrero enamorado y la trágica noticia\n En realidad, Popocatépetl no estaba muerto, sino que se había escondido en la selva y desde allí, comenzó a librar estratégicas y astutas batallas contra el enemigo. Y, al regresar al campamento, sus compañeros, que le habían traicionado, huyeron. \n El joven guerrero regresó al palacio del emperador para contarle lo que había ocurrido, de cómo le habían tendido una trampa y de cómo aún así, consiguió ganar varias batallas. El emperador, roto por el dolor, le comunicó que Izta había muerto de pena, pero que había demostrado tanto valor y honestidad, que le entregaba el imperio para que gobernara él. \n – ¡No lo quiero! ¡No sin ella!- dijo muerto de dolor Popocatépetl."
leyenda1 += "\n El joven tomó entre sus brazos el cuerpo de Izta y se lo llevó de allí. Se retiró a un lugar lejano y construyó con sus propias manos una montaña sobre la que colocó el cuerpo de su amada. Junto a ella, prendió una hoguera que mantenía encendida todos los días y todas las noches. \n Junto a esa montaña, construyó otra, más alta aún, en donde se quedó a vivir el resto de sus días. Para calentarse, también mantenía encendida una pequeña hoguera. \n Con el tiempo, la montaña en donde descansaba Izta se transformó en un hermoso volcán con cuerpo de mujer. Muy cerca, se levanta otro inmenso volcán, donde vivió su enamorado: Popocatépetl."

let leyenda2 = "Cuentan que hace mucho, pero que mucho tiempo, al comienzo de todo, los dioses crearon el sol y la luna, a partir de Nanahuatzin (de él surgió el sol al tirarse a un fuego encendido por el resto de dioses) y Teciciztécatl (el que dio origen a la luna y que fue golpeado por uno de los dioses con un conejo para castigar su soberbia, dejando uno de sus lados a oscuras)."
leyenda2 += "\nPero los dioses se dieron cuenta de que el sol y la luna permanecían quietos, sin movimiento, y a los dioses se les ocurrió matar a alguno de los dioses para que al resucitar, pudieran dotar al sol de movimiento. Sin embargo, uno de los que debía ser sacrificado, Xólotl, se negó a morir. Es más… ¡se escapó! Y el dios del viento, Echécatl, que era el encargado del sacrificio, le fue a buscar."
leyenda2 += "\nResulta que Xólotl se escondió primero en los maizales, convirtiéndose en los pies del tallo del maíz que tiene dos tallos (al que los campesinos llaman xólotl). Y al ser descubierto por el dios del viento, fue a esconderse entre otras plantas, los magueyes. Pero también fue descubierto y de nuevo huyó, esta vez, arrojándose al agua. Y allí es donde se transformó en ajolote, y el lugar donde finalmente fue atrapado por el dios del viento. Desde entonces, el ajolote se convirtió en manjar para los príncipes aztecas."

let leyenda3 = "Cuenta una leyenda azteca que hace mucho, pero muchísimo tiempo, andaba el dios Quetzalcóatl  bastante aburrido. Los aztecas tenían muchos dioses, y Quetzalcóatl era un dios muy bondadoso.\nEl aburrimiento llevó al dios maya a pensar: ¿y si viajo por el mundo transformado en hombre? Y eso hizo: el dios Quetzalcóatl se convirtió en hombre y bajó a la Tierra.\nY andando y andando por el mundo, comenzó a tener hambre. De hecho, llevaba todo el día andando y no había probado bocado. El sol se puso, la luna y las estrellas iluminaron el cielo.\nEl dios se sentó a descansar y de pronto vio a un conejito grisáceo que entraba en su madriguera a comer."
leyenda3 += "– Eh, conejito, ¿qué comes?- le preguntó el dios.\n– Un poco de zacate (hierba de pasto) que encontré- contestó él- Si quieres, puedo compartirlo contigo.\n– Oh, gracias, conejito, pero yo no como zacate.\nEl conejo vio que estaba realmente hambriento y muy cansado…\n– ¿Y entonces, qué comerás?\n– Nada- contestó Quetzalcóatl.\n– Pero… ¡morirás de sed y hambre!\n– Así será…\n– No, eso no  puede ser- dijo de pronto el conejito-. Si quieres, puedes comerme. Yo solo soy un conejo, y tú eres un hombre. Si tienes hambre, debes comerme." 
leyenda3 += "Entonces, el dios Quetzalcóatl, impresionado por la bondad y humildad del conejo, le tomó entre sus brazos, le acarició y le alzó muy alto. La luna lucía muy redonda y blanca. El dios bondadoso miró la luna y luego al conejito y dijo:\n– Tú solo serás un conejo, pero tienes un corazón más bondadoso que el de muchos humanos. A partir de ahora, serás ejemplo para todos. Tu imagen quedará grabada en la luna y así, cada vez que los humanos la miren, recordarán tu enorme gesto.\nDe forma casi inmediata, la imagen del conejito quedó grabada en la luna. El dios Quetzalcóatl dejó al conejo en su madriguera y decidió volver a su mundo, satisfecho al comprobar que hasta los animales más insignificantes tenían un gran corazón."

export {leyenda1, leyenda2, leyenda3}
